name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Copiar código do repositório
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalar dependências
      run: npm install --legacy-peer-deps

    # - name: Executar testes com Jest
    #   run: npm test